# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
      required_version = "1.9.8"

      required_providers {
        aws = {
          version = "5.74.0"
        }
      }
    }

    provider "aws" {
      profile = "development_administrator"
      region  = "ap-northeast-1"

      default_tags {
        tags = {
          repository = "aws_terraform"
          directory  = "development_servvices/."
          service    = "."
        }
      }
    }
