
global:
  scrape_interval:     30s
  evaluation_interval: 30s
  external_labels:
    environment: 'production'
    role: 'monitoring'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093 # CloudMapで名前解決させる必要がある・
rule_files:
  - alert_rules.yml

scrape_configs:
  - job_name: 'blackbox_monitor'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://cdn.takehiro1111.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: blackbox-exporter.manage.in:9115
      - source_labels: [job]
        regex: (.*)-url
        replacement: $1
        action: replace
        target_label: product
