global:
  resolve_timeout: 5m

routes:
    - match:
        severity: critical
      receiver: slack
    - match:
        severity: warning
      receiver: slack

receivers:
  - name: slack_notifications
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#alerts'
        send_resolved: true  # アラート解消時の通知を送るか
        text: |  # 通知メッセージのフォーマット
          *[{{ .Status | toUpper }}] Alert:*
          *Summary:* {{ .CommonAnnotations.summary }}
          *Description:* {{ .CommonAnnotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Instance:* {{ .Labels.instance }}

# 特定のアラートが発生しているときに、他のアラートを抑制するルールを定義。
inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['alertname', 'instance']
