name: auto_update_readme_dir_structure
run-name: ${{ github.workflow }} by @${{ github.actor }}

on:
  schedule:
    - cron: '0 22 * * *'

  workflow_dispatch:

defaults:
  run: 
    shell: bash

permissions:
  id-token: write
  actions: write
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install tree
        run: sudo apt-get install -y tree

      - name: Run auto_update_readme_dir_structure.sh
        run: bash auto_update_readme_dir_structure.sh

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update README with latest directory structure"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
