name: Push ECR & Depoloy ECS 
run-name: ${{ github.workflow }} by @${{ github.actor }}

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docker/locust/**'
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-1
  ROLE_TO_ASSUME: ${{  secrets.AWS_ASSUME_ROLE }}

permissions:
  id-token: write
  contents: read

jobs:
  ecr-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - working_directory: docker/locust
            ecr_repository: locust
    env:
      ECR_REPOSITORY: ${{ matrix.config.ecr_repository }}
    defaults:
      run:
        working-directory: ${{ matrix.config.working_directory }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    # https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS Credentials OIDC
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME}}

    # https://github.com/aws-actions/amazon-ecr-login
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2

      - name: Push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}  # 'Login to Amazon ECR'の結果の中の'repository'の値を参照する
          # docker image tag temp_api_image:latest {アカウントID}.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:sha
        run: | 
          set -eux
          docker image build -t temp_api_image:latest .
          docker image tag temp_api_image:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          docker image push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          echo $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} > image-uri.txt
      
    # https://github.com/actions/upload-artifact
      - name: upload the Artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v4
        with:
          name: image-uri
          path: ${{ matrix.config.working_directory }}/image-uri.txt


  # Deploy
  ecr-deploy:
    runs-on: ubuntu-latest
    needs: [ecr-push]
    strategy:
      matrix:
        config:
          - ecs_cluster: cluster-web
            ecs_service: locust
            ecs_task_difinition_api: .aws/task/locust_task_definition.json
            container_name: locust-container # タスク定義内の"name"と合わせる必要がある。
    env:
      ECS_CLUSTER: ${{ matrix.config.ecs_cluster }}
      ECS_SERVICE: ${{ matrix.config.ecs_service }}
      ECS_TASK_DEFINITION_API: ${{ matrix.config.ecs_task_difinition_api }}
      CONTAINER_NAME: ${{ matrix.config.container_name }}

    steps: 
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Configure AWS Credentials OIDC
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME}}


      # https://github.com/actions/download-artifact
      - name: Download the Artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v5 # uploadと同じバージョン(v4),nameを指定しないとエラーになるので注意。
        with:
          name: image-uri
          path: download/artifacts #ランナーの中でダウンロード先のディレクトリが動的に作成されるのでこちらは任意のパスを記載。 

      - name: Define the image URI
        id: download_image_uri
        run: | 
          echo "IMAGE_URI=$(cat  download/artifacts/image-uri.txt)" >> $GITHUB_OUTPUT

      # https://github.com/aws-actions/amazon-ecs-render-task-definition
      - name: Fill in the new image URI in the amazon ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@cbed19f1b86bbb18f59cfffde7107b93cc9b75da # v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION_API }}
          container-name: ${{ env.CONTAINER_NAME}}
          image: ${{ steps.download_image_uri.outputs.IMAGE_URI }}

      #  https://github.com/aws-actions/amazon-ecs-deploy-task-definition
      - name: Deploy ECS task
        uses: aws-actions/amazon-ecs-deploy-task-definition@1beffbdddb3eb5f83c7a746c3e9bafeccdccbbaa # v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
