name: terraform_deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - 'stg/**'
  workflow_dispatch:


env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.7.5


  jobs:
    terraform1:
      name: terraform plan
      runs-on: ubuntu-latest
  
      permissions:
        id-token: write
        contents: read
        pull-requests: write 
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Configure AWS credentials via OIDC
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: ${{env.AWS_REGION}}
            role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }} # S3アクセス権限を持つIAMロール
            role-session-name: GithubActions_AssumeRole
            #CloudTrailログ等の監査ログでどのセッションがどの操作を行ったのかを追跡するために設定。
              
        - uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: ${{ env.TF_VERSION }}

        - name: Validate
        run: |
          terraform validate

        - name: Fmt
          run: |
            terraform fmt
          
        - name: Init
          id: init
          run: |
            terraform init
